# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ac0d9cb4d5bc8783fd8af2c6de95790e44b6624c19fa6db5748a2787bdfa8f86ec5df49faca02d0d1368e4fa00337bd876213d5319dba630e3a9c252d7b173bc

test:
  secret_key_base: fe97fafb13a463b22c8041b85c18d3825f282915a362435c32d54b397ed4afd5707ce74633c0fcaa4ddbc8f268779956418e452cb9cfc950c0bd1f7e13c8e84f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
